"""
Blank web template — minimal HTML/CSS/JS scaffold + GitHub Actions CI.
"""


def get_files(repo_name: str, description: str = "") -> list[dict]:
    """Returns a list of {path, content} dicts ready to be pushed to the repo."""
    display_name = repo_name.replace("-", " ").title()
    desc_line = description or f"A web project generated by Plumberito."

    return [
        {
            "path": "README.md",
            "content": f"# {display_name}\n\n{desc_line}\n",
        },
        {
            "path": "index.html",
            "content": f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{display_name}</title>
  <link rel="stylesheet" href="style.css" />
</head>
<body>
  <h1>{display_name}</h1>
  <p>{desc_line}</p>
  <script src="main.js"></script>
</body>
</html>
""",
        },
        {
            "path": "style.css",
            "content": """*, *::before, *::after { box-sizing: border-box; }

body {
  margin: 0;
  font-family: system-ui, sans-serif;
  background: #fff;
  color: #111;
}
""",
        },
        {
            "path": "main.js",
            "content": "// Entry point\n",
        },
        {
            "path": ".github/workflows/ci.yml",
            "content": f"""name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check required files exist
        run: |
          for f in index.html style.css main.js; do
            [ -f "$f" ] || {{ echo "Missing $f"; exit 1; }}
          done

      - name: Lint HTML
        uses: anishathalye/proof-html@v2
        with:
          directory: .
          check_external_hash: false
""",
        },
    ]
