/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-container": "#cc0000",
        "secondary-container": "#e4e2e1",
        "surface-container-high": "#efe7da",
        "secondary-fixed": "#e4e2e1",
        primary: "#9e0000",
        "outline-variant": "#e8bdb6",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "on-surface": "#1e1b13",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        error: "#ba1a1a",
        "on-secondary": "#ffffff",
        "on-primary-container": "#ffdad4",
        secondary: "#5f5e5e",
        "surface-dim": "#e0d9cc",
        tertiary: "#544c3b",
        background: "#fff8ef",
        "inverse-primary": "#ffb4a8",
        "surface-tint": "#c00000",
        surface: "#fff8ef",
        "surface-container": "#f5ede0",
        "on-background": "#1e1b13",
        "surface-container-highest": "#e9e2d4",
        "inverse-on-surface": "#f7f0e2",
        "tertiary-container": "#6c6452",
        "surface-container-low": "#faf3e5",
        "inverse-surface": "#333027",
        "surface-variant": "#e9e2d4",
        outline: "#926e69",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Space Grotesk", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      borderRadius: {
        DEFAULT: "0px",
        none: "0px",
        sm: "0px",
        md: "0px",
        lg: "0px",
        xl: "0px",
        "2xl": "0px",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
